flasher_noty:
    scripts:
        cdn:
            - 'https://cdn.jsdelivr.net/npm/@flasher/flasher-noty@1.3.2/dist/flasher-noty.min.js'
        local:
            - '/vendor/flasher/flasher-noty.min.js'

    styles:
        cdn:
            - 'https://cdn.jsdelivr.net/npm/@flasher/flasher-noty@1.3.2/dist/flasher-noty.min.css'
        local:
            - '/vendor/flasher/flasher-noty.min.css'
