flasher_noty:
    scripts:
        cdn:
            - 'https://cdn.jsdelivr.net/npm/@flasher/flasher-noty@1.2.4/dist/flasher-noty.min.js'
        local:
            - '/vendor/flasher/flasher-noty.min.js'
